# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baebc04e98c4878b0a16e7729102a037b507750aa4d12ef3dad5210f35c32ae44e6dbce7a6b013255695bb40b557dcf7e13c7e04a5c360eff5bb0a11780bef21

test:
  secret_key_base: 8c9ab118031a3327b952fc41cb0c571fa9fc6ec105a123c2a0cbcd95e37d1b7cf894206fd07373849fe5bc9ac8415f25789a75180d6405cf5e3fcd61f08aa13b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
